
version: 2

models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: customer_purchases
      description: "the total purchases for each customer in Snowflake sample data"
      columns:
          - name: c_custkey
            description: "The primary key for this table"
            tests:
                - unique
                - not_null